name: Bump version
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: sbe-arg/github-tag-action@tag-test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
